### ISSUE TITLE
Error with newline command

### ISSUE THREAD

**Issue by subhogue** [xleon/I18N-Portable#1]
When trying to translate the string "this is a string\nthis should be a new line." you instead of getting the expected value of:
'this is a string
this should be a new line.'

you instead get exactly what you put in:
"this is a string\nthis should be a new line."

Haven't looked through source code yet, about to do so and will update if I find anything, but I'm hoping to find a way to fix this or some other way to do a newline command.

**Comment by subhogue** [comment]
After looking through the code closer and running a few tests I found that it is possible to get the desired result though the process is not ideal. To get the desired result you just use the Format string as follows:
str = this is a string{0}this is a newline.
string translatedString = "str".Translate("\n");

the result the takes the desired form of:
'this is a string
this is a newline.'

I do hope that this is fixed in the future to make it so '\n' can be used within the translation string without using a work around.

**Comment by xleon** [comment]
I need to make some tests. What platform/system are you using?

**Comment by xleon** [comment]
I´ve just tested this. It´s not about the platform. Escape sequences like `\n` or `\r\n` don´t make any effect in string objects. When reading the text file,`\n` becomes `\\n`.

The easy workaround:

```csharp
var translation = "str".Translate().Replace("\\n", System.Environment.NewLine);
```
I will probably introduce that conversion in the next release, or maybe adding a new initialization parameter to avoid breaking existing implementations.

**Comment by xleon** [comment]
https://github.com/xleon/I18N-Portable/releases/tag/0.2

**Comment by xleon** [comment]
You can now use line breaks and multi-line as well:

    TextWithLineBreakCharacters = Line One\nLine Two\r\nLine Three

    Multiline = Line One
        Line Two
        Line Three
