### ISSUE TITLE
Support multiple resource formats

### ISSUE THREAD

**Issue by mmfoscarpeerio** [xleon/I18N-Portable#19]
Is there a possibility when doing the Init() of the I18N class to decide which format support (txt/json/resx)?

**Comment by xleon** [comment]
Not at the moment, but that´s already planned for the next release: https://github.com/xleon/I18N-Portable/issues/18

You will be able to:

    I18N.Current.AddLocaleParser(ILocaleParser).Init(...);

There will be a default locale parser for .txt files, but other parsers will be added in the future. 
The main reason to provide an `ILocaleParser` interface is that you could implement parsers for whatever format you need, like specific json structures, etc.

This task is almost done. I´ll make a new release asap (probably next week)

**Comment by xleon** [comment]
[PO](http://pology.nedohodnik.net/doc/user/en_US/ch-poformat.html) format seams like a good candidate as it is widely used

**Comment by xleon** [comment]
For json I´m going to add the following formats as default:

__key value pairs:__
    {
        "one" : "uno", 
        "two" : "dos" 
    }

__list of objects__
    [
        { "key" : "one", "value" : "uno" },   
        { "key" : "two", "value" : "dos" }
    ]

**Comment by xleon** [comment]
I realized this introduces a new dependency in the project that is Json.Net and one of the goals of this library is keeping things simple.

Given that a json parser/reader takes just a few lines of code, I´m going to close/dismiss this issue for now unless there´s a real demand for it, in which case I may create a separated nuget for each parser/reader that people could just plug into it.

However, https://github.com/xleon/I18N-Portable/issues/18 is done already, meaning that other file extensions can be used (like _en.json_ or _ru.somefreakyformat_) and you will be able to add new readers easily.

Here´s an example for json key-value pairs:

__en.json__
```
{
  "one": "one",
  "two": "two",
  "three": "three",
  "Mailbox.Notification": "Hello {0}, you´ve got {1} emails",
  "TextWithLineBreakCharacters": "Line One\nLine Two\nLine Three",
  "Animals": "List of animals",
  "Animals.Dog": "Dog",
  "Animals.Cat": "Cat",
  "Animals.Rat": "Rat",
  "Animals.Snake": "Good\nSnake",
  "Fruit.Orange": "great orange",
  "Fruit.Apple": "big apple",
  "Fruit.Banana": "nice banana"
}
```

```
public class JsonKvpReader : ILocaleReader
{
    public Dictionary<string, string> Read(Stream stream)
    {
        using (var streamReader = new StreamReader(stream))
        {
            var json = streamReader.ReadToEnd();

            return JsonConvert
                .DeserializeObject<Dictionary<string, string>>(json)
                .ToDictionary(x => x.Key.Trim(), x => x.Value.Trim().UnescapeLineBreaks());
        }
    }
}
```

```
I18N.Current
    .AddLocaleReader(new JsonKvpReader(), ".json")
    .Init(GetType().Assembly);
```

This is currently in a [feature branch](https://github.com/xleon/I18N-Portable/tree/feature/readers) but I´ll merge into master once it´s ready and then a new nuget will be released

**Comment by xleon** [comment]
Here´s the new project for json readers: https://github.com/xleon/I18N-Portable/tree/master/I18NPortable.JsonReader

In case anyone wish to contribute, a new project should be created for any new format

**Comment by xleon** [comment]
Ok, I finally created a nuget for the json readers an updated the readme explaining how to create new readers and contributing: https://github.com/xleon/I18N-Portable#supported-formats

**Comment by mmfoscarpeerio** [comment]
Thanks. With the ILocaleReader it can be used any taste of JSON library.
