### ISSUE TITLE
Android Inflate exception

### ISSUE THREAD

**Issue by clovs** [xleon/I18N-Portable#36]
Hello,

I installed the package in a proper xamarin forms project.  
(I'm using Visual studio for Mac)

iOS works fine, But on Android I got an Android.Views.InflateException.

"Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.v7.widget.Toolbar"
Caused by: java.lang.NoClassDefFoundError: Failed resolution

Have you any idea why I18nPortable is causing this exception?
Thanks by advance

**Comment by xleon** [comment]
Did you add I18NPortable nuget to the android project?

**Comment by clovs** [comment]
Yeah I did,
The exception become just after the installation on the I18NPortable package.
on LoadApplication(new App()); --> from MainActivity.cs

If I delete the package the exception is gone.

- [ ] I fix this issue by deleting Droid/bin & Droid/obj folders on the project just after I18NP. installation
There some unknown conflict in some XML files.

So it's not necessary an Issue from I18nPackage, but can be relevant for some people trying to install it.

Thanks for your support
Nice Package 👍
