### ISSUE TITLE
Binding in  XAML not working with dot (Syntax error)

### ISSUE THREAD

**Issue by clovs** [xleon/I18N-Portable#37]
Hello,
We can't access to 
`AnimalsPage.DogLabel = Dog 🐶`

directly by binding in xaml like below (we got a syntax error, cause of the dot):
` <Label Text="{Binding Strings[AnimalsPage.DogLabel]}" />`

Maybe you have an alternative to get access to AnimalsPage Values with kind of this xaml syntax?
` <Label Text="{Binding AnimalsPage[DogLabel]}" />`

Thanks in advance for your feedback.

**Comment by xleon** [comment]
That´s a limitation for XAML bindings in xamarin.forms. However it works fine on UWP XAML.
I use underscores instead of dots in xamarin.forms
