### ISSUE TITLE
Locales not show on each item listview when use MVVMCross for Android

### ISSUE THREAD

**Issue by trungluc1996** [xleon/I18N-Portable#39]
Hello,
I'm having a problem when using it to Bind multi language for the TextView on each item ListView.
I use the **local:MvxBind="Text Strings[Key]"** but it does not show. With other textviews, it works.

Does anyone know how to fix it?
Thanks in advance for your feedback!

**Comment by xleon** [comment]
Did you add the indexer Strings to the view model?

**Comment by trungluc1996** [comment]
Yes, I added it. All the textviews in the activity are work. But this is a text view in the itemtemplate listview, is there a way to display it?

**Comment by xleon** [comment]
Bindings won´t work like that in item templates. For that I suggest to manually assign strings on code behind: `whatever.Text = "key".Translate();`
