### ISSUE TITLE
Changing languages without recreating pages

### ISSUE THREAD

**Issue by bhyip23** [xleon/I18N-Portable#40]
Is it possible?  Right now setting I18N.Current.Locale or I18N.Current.Language will not change the text of any pages already on the stack.

**Comment by xleon** [comment]
It´s possible, but it depends on how your translations are set. If you assigned by `text = "something".Translate();` then it´s not possible. But it should work if  you use bindings: https://github.com/xleon/I18N-Portable#data-binding

**Comment by bhyip23** [comment]
Hmm, I am using bindings `<Button Text="{Binding Strings[Start]}"` and it doesn't seem to be working...

**Comment by xleon** [comment]
If you take a look at the samples you´ll see a button to change language. All strings will be updated as soon as you pick one of them. I can´t figure out what´s your problem without knowing a bit more about your code
