### ISSUE TITLE
Auto-wire iOS xib/storyboard elements

### ISSUE THREAD

**Issue by xleon** [xleon/I18N-Portable#8]
It would be handy to get xibs or storyboards automatically translated. 

The idea is to set translation keys in xcode inspector, either way on User Defined Runtime Attributes:

![captura de pantalla 2017-02-07 21 02 22](https://cloud.githubusercontent.com/assets/145087/22709047/bc0a1a8a-ed78-11e6-8ee2-dec1a7bd927d.png)

or maybe an Accessibility label:

![captura de pantalla 2017-02-07 21 03 22](https://cloud.githubusercontent.com/assets/145087/22709093/e157bb9e-ed78-11e6-96d5-624b9ccb8557.png)

A UIViewController method extension could handle and translate all views with keys defined.

**Comment by SeeD-Seifer** [comment]
I've implemented **Runtime Attributes** and shortly described it in the a gist:
https://gist.github.com/SeeD-Seifer/d90df33269a9691c15bad2992534a459

**Comment by xleon** [comment]
Thinking this twice... seams like out of the scope of this library
