### ISSUE TITLE
Load remote locales and cache on local storage

### ISSUE THREAD

**Issue by xleon** [xleon/I18N-Portable#9]
Besides the embedded resources it would be handy to have the locales on a server so someone could update the strings of an app without releasing/publishing a new version. 

The library would silently download the server files and update a local cache.
~~For this to happen we would copy the embedded resources to the file system at the app initialization.~~ Locales would be override with new updates after a sanity check of the downloaded file.  

An expiration date could be passed to the load call to avoid unnecessary requests on every app restart.

TODO list:

- [ ] Define `ILocaleProvider` interface
- [ ] Do not rely always on embedded resources to create the list of available locales => Create a fluent method (optional) to pass the supported languages. This way we can have just one default locale embedded and load the rest of them remotetly
- [ ] ILocaleDownloader: responsible to download a single resource (retry 2 or 3 times) and provide a result stream
- [ ] Utility to download all locales in parallel
- [ ] Define strategy to expire locales and when we should re-download
- [ ] Default cache implementation => save files to a known system folder (bait and switch)
- [ ] Create `CachedRemoteLocaleProvider`
- [ ] Integration tests

**Comment by mr-wheelkers** [comment]
Hi xleon, Found your lib. Looks great. We also need to create a loading process for remote resources. I will fork this one and add an extension point for resource acquisition.

**Comment by xleon** [comment]
Hi. I didn´t even start this task yet but I really need it for the project I´m doing. The client just keeps changing strings all the time.
What do you mean by "loading process"? number of files downloaded / total or bytes downloaded?

**Comment by mr-wheelkers** [comment]
Hi Diego,

We have our translation situated on a web-site. So we want to update the
translation doc every time the app is started.
I've already changed your code a bit to support this functionality. I'm
working on the actual loader code now.

I will make a pull-request after I finish. And would be happy if you will
apply it.

Thanks,
Sviatoslav Kolesnyk

**Comment by xleon** [comment]
Cool. I´ll take a look at your PR and see how it can fit with the current plans. Actually I will be expanding the library to go beyond pure PCL as it needs to do platform specific stuff like accessing file system stuff and wiring native views.

**Comment by xleon** [comment]
Just FYI, the idea is not only loading the remote locales, but caching them on the local file system. That way a network failure would not prevent the app from working as expected. To do so, new projects are needed in the solution to target every platform.

**Comment by mr-wheelkers** [comment]
Yes, I understand. I have cross-platform solution for iOS/Android for file
storage. If you like, I can share it too.

**Comment by xleon** [comment]
LGTM

**Comment by xleon** [comment]
I have one concern with this functionality. Loading remote locales is an async process. I18N should be ready on app start and delaying app start (waiting for server to respond) doesn´t look like a good idea for obvious reasons. 

The best possible solution I can think of is having both providers, embedded and remote. The embedded one would load translations on app init. The remote provider would update translations on the background.

A decision has to be taken:

1. Let the developer choose the strategy, allowing an only-remote provider
2. Make the embedded provider mandatory, and the remote provider as secondary one

Not sure yet. What do you think?

**Comment by mr-wheelkers** [comment]
The main goal of strategies is to let the developer choose the desired
approach that can be a combined strategy with remote + cache + fallback
embedded resource.
And this strategies are going to be per language, so for default fallback
language there will be an embedded resource and for others there will be
no.
I'm currently finishing other tasks and will provide pull-request with
strategies EOD.

**Comment by xleon** [comment]
Just an update. This idea is evolving a lot and I think it will be an strong "selling" point of this library.
That´s why I added it back to milestone 1.0.

Loading remote files logic should be separated from the cache strategy, as they are 2 different things. There will be an interface (i.e: `IRemoteLocaleLoader`) with a default implementation using `HttpClient` logic, but custom implementations will be allowed. For instance, you may want to access authorized web api resources to get your translations. 

In the other hand, a local cache could be implemented with the local file system by backing up the remote files/streams to simple files and that is probably going to be the default strategy. But as a user of the library, I may want to store translations in a database, so a new interface (i.e: `ILocaleCache`) should be introduced. 

Having those interfaces implemented (`I18NPortable` should provide a default implementation out of the box), we could mix them in a `RemoteCacheLocaleProvider` who would coordinate the whole thing.

I´m already working/thinking about how to make this easy for everyone but keeping polymorphism on each piece of the party.

**Comment by mr-wheelkers** [comment]
The per language difference was brought by our company requirements were default language should have a local fallback strategy and all the others should be cache-only.

**Comment by mr-wheelkers** [comment]
> Otherwise it should be added as a plugin, with its own nuget. 
We can extend a little bit here - we can have like core project with base interfaces and classes an couple of satellite nuggets with realizations (local, remote, db). And the base lib should be extension friendly.

**Comment by xleon** [comment]
Yes, that´s the idea

**Comment by xleon** [comment]
I´ve been thinking about this again and I totally changed my mind. Loading locales on runtime from a remote source is an edge case. Instead I´m doing a console tool to import locales from a Google Sheet. Closing this
